### ISSUE TITLE
Julia version available

### ISSUE THREAD

**Issue by milankl** [LLNL/zfp#103]
Hey Peter, I just wrote a wrapper for the Julia language, available here: https://github.com/milankl/ZfpCompression.jl - the C library is automatically installed too. At the moment only the main functionality is supported, but this might change in the future.

**Comment by lindstro** [comment]
Hi Milan, thanks for sharing the news and for making your code available.  Do you mind if I add a link to it from [here](https://computing.llnl.gov/projects/floating-point-compression/related-projects)?

Would it make sense to [embed a header](https://zfp.readthedocs.io/en/release0.5.5/high-level-api.html#c.zfp_write_header) so that the user does not have to specify the compression parameters in `zfp_decompress`?  This is what the [Python wrappers](https://zfp.readthedocs.io/en/release0.5.5/python.html#zfpy.decompress_numpy) do.

**Comment by milankl** [comment]
Please yes, you are more than welcome to add it! Adding a header definitely makes sense - will do soon. Thanks Peter!

**Comment by milankl** [comment]
fyi, header was added ;)
