### ISSUE TITLE
Thread safety of underlying functions

### ISSUE THREAD

**Issue by shauryapatel1995** [LLNL/zfp#124]
Hi, 
I am using Cuda to perform compression and decompression. I was wondering if the underlying methods of zfp like zfp_stream_open etc. are CPU thread-safe?

**Comment by lindstro** [comment]
I'm afraid not.  No operations on `zfp_stream` are explicitly thread safe, though it's possible that some of them are implicitly, e.g., if they do not modify their arguments.  As it turns out, `zfp_stream_open` is one of the safe functions, but it is generally not safe for multiple threads to simultaneously pass the same `zfp_stream*` to zfp functions.

I can perhaps make some suggestions if you provide more details on what it is you're trying to do.

**Comment by lindstro** [comment]
@shauryapatel1995 Unless you have further questions on thread safety, I would like to close this issue.

**Comment by shauryapatel1995** [comment]
Hi @lindstro sure go ahead and close it! I need to come up with a more detailed question, I can open that as an issue later. Thanks for your response!
