### ISSUE TITLE
Bit sizes of 1 reported by `zfp_encode_block_double_4`

### ISSUE THREAD

**Issue by cpviolator** [LLNL/zfp#129]
We are compressing 4D double precision data of extent 32^4 in place, using a modified version of the 2D `inplace.c`. We get excellent data reproduction. However, `zfp_encode_block_double_4` reports that the first 128 block bit sizes are ~9000 and all subsequent blocks are of size 1 for a blocking size of 4^4. We list here the various compression ratios for the same data set using blocks of 2^4, 4^4, 8^4

block size = 2: (27.06x)
block size = 4: (56.17x)
block size = 8: (898.43x)

Our question is this: is the reporting of bit sizes of 1 reasonable behaviour for the `zfp_encode_block_double_4` function? We hare happy with the data reproduction, but we are suspicious of the compression ratios.

**Comment by lindstro** [comment]
I'm not sure what you mean by "block size."  A 4D zfp block is always 4^4 values.  Since array dimensions are not always multiples of four, some blocks near the array boundary will necessarily have to be padded to 4^4 values, and there are encode functions (e.g., `zfp_encode_partial_block_strided_double_4`) that take such partial blocks (of size 1 <= n <= 4) and inserts padding.  Is that what you mean by block size?  Note that the partial block size cannot be larger than 4.  Or do you perhaps mean the number of 4^4 zfp blocks along each dimension, e.g., block size = 8 would imply an (8 * 4)^4 = 32^4 domain?

Independent of this, blocks can indeed compress to a single bit if they consist of all-zeros or if all values fall below the absolute error tolerance in fixed-accuracy mode.  zfp will reconstruct such blocks as all-zeros, which would respect the tolerance.

**Comment by cpviolator** [comment]
@lindstro Thank you for the reply. Our data array dimensions are always divisible by 4 (for these tests) and for the 4D compression we will restrict to a blocking of 4^4 from now on.

Our first pass at compression performed 32 independent compressions on blocks of 32*32*32 data using `zfp_encode_block_double_3` and `zfp_decode_block_double_3` with a 4^3 blocking scheme. This gave us excellent reproduction and an average compression ratio of 1.82 for each time slice.

The zeros (and single bit blocks) were the clue to my error: not properly transferring temporal data to the array. With the correction I find a very reasonable 1.76x compression of 4D data.

Thank you very much for the clarification and speedy reply.

**Comment by lindstro** [comment]
Glad to hear you found the issue.  1.82x is not a very impressive compression ratio, however, for lossy compression.  Are you using lossless mode or very tight tolerances?

**Comment by cpviolator** [comment]
Very tight tolerance (1e-9 gives us a 2x) and our data is not particularly well correlated to begin with. However, even a 2x is a great boon to us as we will be frequently moving the data from global GPU memory to the threads. Compression and decompression of the data is tiny compared to the transfer latency, and the set up costs we do to prepare the data so it is in spatially correlated form is completely amortised.

I see that there is support for CUDA. Can one use 4D encoding/decoding on the GPU? At the moment we are just prototyping with data on the CPU to get a feel for the efficacy. We will need both 4D and 3D routines for all our data types.

**Comment by lindstro** [comment]
We currently don't have CUDA support for 4D compression, but it's high on our to-do list.  We're also in the process of adding CUDA (and HIP) compression modes other than fixed rate, including fixed precision and accuracy.  We should have this capability available on a feature branch in the coming weeks.

For now, we don't have support for the low-level API on the GPU.  For what you're doing, it likely makes sense to use the high-level API anyway so that you can take advantage of data parallelism.

**Comment by cpviolator** [comment]
That's awesome to hear! I will explore the high level API and adjust our code. When we have performant CUDA compression I will ensure that we report back with benchmark data.
