### ISSUE TITLE
Support for parallel random access compressed integer array

### ISSUE THREAD

**Issue by Char-Aznable** [LLNL/zfp#152]
Hi, @lindstro Thanks for this great tool! I am interested in using the array1 template for storing a large integer array. The array represents the indices to the column of another 2d array. In side the 1d index array, the neighboring elements have strong correlation with each other (they are actually from Monte Carlo sampling). The usage case is to read the 1d array and appending new elements to it. My questions are: 
1. Is this usage case supported? 
2. Can the read and write be done safely with OpenMP parallel threads? I am actually using Kokkos's parallelism with OpenMP backend
3. If this is supported, what are my options of compression/decompression algorithm and what kind of random access throughput and compression ratio should I expect? 

I hope this is not too many questions. Thanks for your attention!

**Comment by lindstro** [comment]
> Is this usage case supported?

zfp currently does not support integer compressed-array classes, though with our recent refactoring of these classes, it is trivial to add such support by adding missing template specializations to `zfpcpp.h` and `zfp/traits.h`.  I spent a few minutes playing with this, and while the code compiles, I'm seeing off-by-one "rounding errors" in the array even when a high enough rate is specified.  The reason for this is that the zfp transform, which performs integer divisions by two, sometimes loses the least significant bit.  This is not a big deal for floating-point data (those least significant mantissa bits are often lost in floating-point arithmetic anyway), but clearly it's undesirable for integer arrays if you require lossless compression, as I suspect you do in this case.

This issue can be resolved by scaling the integers by 2^(2 * (d + 1)) in d dimensions, e.g., by 16 for 1D arrays, and then rescaling them when accessing them through the array.  Clearly, this is not a very elegant solution, but it seems to work:

```
#include <iostream>
#include "zfparray1.h"

int main()
{
  int size = 100;
  const double rate = 8;

  // define integer or floating-point array
#if WITH_INTEGER_ARRAY
  zfp::array1<int> a(size, rate);
  int scale = 4;
#else
  zfp::array1<float> a(size, rate);
  int scale = 1;
#endif

  // initialize array
  for (int i = 0; i < a.size(); i++)
    a[i] = (i - size / 2) * scale;
  a.flush_cache();

  // print array
  for (int i = 0; i < a.size(); i++)
    std::cout << (a[i] / scale) << std::endl;

  return 0;
}
```

I've added support for integer arrays on a separate feature branch `feature/integer-arrays` (too late to get it into the next release).  If it's too cumbersome to have to manually scale values, you can always use `float` or `double` arrays and round such values to integers.

> Can the read and write be done safely with OpenMP parallel threads? I am actually using Kokkos's parallelism with OpenMP backend

zfp arrays can be made thread safe: see [this FAQ](https://zfp.readthedocs.io/en/release0.5.5/faq.html#q-thread-safety).  See also the diffusion C++ example for how to support parallel read and write access.

> If this is supported, what are my options of compression/decompression algorithm and what kind of random access throughput and compression ratio should I expect?

I'm not sure what you mean by options for compression/decompression algorithm.  There's the default zfp codec.  You can also define your own codec (see https://zfp.readthedocs.io/en/develop/arrays.html#codec-1), but adopting new compression algorithms is not trivial since they need the ability to compress tiny blocks of 4 values (in 1D) independently.

It is difficult to say what throughput to expect, as it depends greatly on access pattern and compression ratio.  As far as compression ratio goes, you specify that yourself for fixed-rate arrays, but then you are not guaranteed lossless compression.  To achieve lossless compression, you can use zfp's new `const_array` classes, but they support only read access.  We have an implementation of variable-rate read-write arrays that in principle support lossless compression, but they're not quite yet ready for production use.

**Comment by Char-Aznable** [comment]
@lindstro Thank you so much for adding the new branch for this! I will try it out. But I am still confused in terms of the compression rate for integer array:

1. Does the requirement (in https://zfp.readthedocs.io/en/develop/faq.html#q-granularity) of `word_size / 4^d` bits per value of random access compressed array apply to integer case? I see you use rate of 8 bits in the above example so I guess the answer is no? 
2. You mention that fixed-rate array doesn't guarantee lossless compression. Is this the cause for what you said about losing the least significant bit? Again in your example, does the code give lossless compression after the scaling by 16? My application unfortunately will only work with lossless compression. 
3. Does the scaling by 16 depends on the exact integer type? Do I need a different factor for signed vs unsigned and 32 vs 64 bit?

Thanks again for your help!

**Comment by lindstro** [comment]
> @lindstro Thank you so much for adding the new branch for this! I will try it out. But I am still confused in terms of the compression rate for integer array:
> 
> 1. Does the requirement (in https://zfp.readthedocs.io/en/develop/faq.html#q-granularity) of `word_size / 4^d` bits per value of random access compressed array apply to integer case? I see you use rate of 8 bits in the above example so I guess the answer is no?

Yes, it does--good catch.  In this case, the rate is rounded up to 16 bits/value using the default word size of 64 bits.  You can change the word size at compile time to be 8 bits, which for 1D arrays would give you 2-bit rate granularity.

> 2. You mention that fixed-rate array doesn't guarantee lossless compression. Is this the cause for what you said about losing the least significant bit?

That is one source of errors in zfp, but there are others in fixed-rate mode.  Due to the [pigeonhole principle](https://en.wikipedia.org/wiki/Pigeonhole_principle#Uses_and_applications), you cannot achieve compression unless some inputs also result in expansion.  So in fixed-rate mode, if the values you want to compress have a precision larger than the rate, then there are some inputs that simply cannot be represented without loss.  That's just a "fundamental theorem" of compression and not something unique to zfp.  In variable-rate mode, we allow worst-case inputs to be expanded so that we can support lossless compression.  If you need lossless compression, then I would not use zfp's fixed-rate arrays.  You may as well represent the values uncompressed at the minimal precision needed.

> Again in your example, does the code give lossless compression after the scaling by 16? My application unfortunately will only work with lossless compression.

It does for the range of integers used in the example, which require only 7 bits of precision (notice that the rate is higher than the precision).  But as mentioned above, you cannot meaningfully ensure lossless compression in fixed-rate mode.

> 3. Does the scaling by 16 depends on the exact integer type? Do I need a different factor for signed vs unsigned and 32 vs 64 bit?

No, the scaling depends only on the dimensionality of the array.

**Comment by lindstro** [comment]
@Char-Aznable Is there anything else we can help with before we close this issue?  Since you need lossless compression, I would point you to zfp's `const_array` classes on the `develop` branch, though there currently is an issue with thread-safe access (see #154).  The `const_array` classes also assume that the array is initialized only once and that read-write access is not needed.

**Comment by Char-Aznable** [comment]
@lindstro Thanks for all the help! I am currently busy with other stuff so I haven't got the chance to work on implementing what you suggested into my code. I will close this for now and maybe come back later if I come up with more questions.
