### ISSUE TITLE
Increment develop version after each release.

### ISSUE THREAD

**Issue by brtnfld** [LLNL/zfp#155]
To help CI apps testing using zfp, it would be helpful if the version of develop could be different from the released version.

**Comment by lindstro** [comment]
This is a bit tricky.  `develop` is constantly in flux, so there's no single version that you can depend on for any of its features.  Also, if we were to increment it now to, say, 0.5.6, how would some given snapshot in time of `develop` be distinguished from the actual future 0.5.6 release, which may have features not yet on `develop`?  In what circumstance would you would want to depend on zfp's `develop` branch rather than on official releases?

I'm willing to consider changes to how we version `develop`, but I need to understand better what we're trying to solve.

**Comment by brtnfld** [comment]
When I check out develop and get the version, it reports 0.5.5. But it is not the released 0.5.5, so the version meaning for develop is not correct in that sense. Develop 0.5.6 might not be the actual 0.5.6 release, but it is for sure not the 0.5.5 release.

How are snapshots currently versioned? For example, would they be snapshots based on versions 0.5.5 or 0.5.6? 

For HDF5, we version the develop branch as the next major release (1.14.0). Once 1.14.0 is released, develop will be 1.16.0. We can also release experimental releases (odd-numbered), as we did for 1.13.0, which is based on develop, but develop remains 1.14.0.
Snap-shots and release candidates are versioned 1.x.x-n, with n beginning at 1 and incremented for each snapshot or release candidate. For example, we had several release candidates for 1.13.0, and the last one was 1.13.0-7. We are currently working on 1.13.1-1. I guess it depends on your branch/release model, which I'm not familiar with for zfp.

For CGNS, we follow this model
 https://nvie.com/posts/a-successful-git-branching-model/
and develop gets incremented when a release is made because the next release will be off of develop. We tag them with the version they represent when we have released candidates and add "rc1,rc2,..." but the main version would return as the pre-released version.

It is not a matter of depending on a feature for develop. It is convenient to try for CI both the released versions and develop to catch early issues that would require possible changes and to make those before the official release. For example, I would like to add zfp develop to CI testing for H5Z zfp, and I have a check if version <= 0.5.5 to select the correct data type. Currently, though, this does not work because develop is labeled as version 0.5.5

**Comment by lindstro** [comment]
True that develop != 0.5.5, but also develop != 0.5.6.  I do, however, get your point about early testing and not being able to rely on the version number on the develop branch.  We'd need something like 0.5.5.X, with X changing with each push/PR and/or commit, though that gets quite cumbersome to manage in practice since between releases we might have hundreds of commits (so far we have more than 400 since the 0.5.5 release).

We, too, use GitFlow as our branching model.  We have multiple feature branches in flight at any one time, which tend to be very long-lived until they are ready to be merged into develop for the next release.

From a practical standpoint, it probably makes sense to distinguish only official releases from the current develop branch, so maybe it's sufficient to add a Boolean to the version number that would allow distinguishing 0.5.5 <= 0.5.5.develop < 0.5.6.  That's akin to the odd/even HDF5 releases.

One day we will transition to version 1.0.0, and at that point we anticipate changing how we number versions, possibly with more frequent releases/patches.

Until we come up with a good solution, the best I can suggest is to externally define something like `ZFP_DEVELOP` (or to add such a macro to zfp.h on your own fork) when testing your code with the zfp develop branch.  I'm hesitant to change how we're doing versioning between releases, but it would be good to have a better plan in place once 0.5.6 is released.

**Comment by lindstro** [comment]
@brtnfld We released 1.0.0 today, which hopefully addresses this issue.  `ZFP_VERSION_DEVELOP` will be defined whenever `develop` differs from the most recent release.  We have also added `ZFP_VERSION_TWEAK` for snapshots, which will be updated when feature branches are merged into `develop` between official releases.  See also the new `ZFP_MAKE_VERSION` family of macros.  Please let us know if this addresses your concern.

**Comment by brtnfld** [comment]
Thanks, I think that solution will work with H5Z-ZFP
