### ISSUE TITLE
Python 3.11 wheels

### ISSUE THREAD

**Issue by jakirkham** [LLNL/zfp#192]
Would it be possible to add wheels for Python 3.11?

**Comment by da-wad** [comment]
Zfpy wheels for 1.0.0 were uploaded to PyPI over a week ago :-) 
https://pypi.org/project/zfpy/1.0.0/#files

**Comment by jakirkham** [comment]
Thank you! 🙏

Missed it as I was looking at `1.0.0.post3`. Though think `1.0.0` should work well :)

**Comment by DimitriPapadopoulos** [comment]
Neither `1.0.0rc*`n or `1.0.0post*` are GitHub [Releases](https://github.com/LLNL/zfp/releases)/[Tags](https://github.com/LLNL/zfp/tags). These seem to be handled elsewhere.

Perhaps `0.5.5` and `1.0.0` are the stable versions we should use. In that case, it is disturbing that `pip install` will install `1.0.0` with Python 3.11, and `1.0.0post3` with Python 3.10:
```
$ pip --version
pip 22.3 from /home/username/.local/lib/python3.10/site-packages/pip (python 3.10)
$ 
$ $ pip install --user zfpy
Collecting zfpy
  Downloading zfpy-1.0.0.post3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (729 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 729.3/729.3 kB 9.2 MB/s eta 0:00:00
Installing collected packages: zfpy
Successfully installed zfpy-1.0.0.post3
$ 
```

**Comment by da-wad** [comment]
Yes, `0.5.5` and `1.0.0` are the stable versions.

The reason there are post releases is failed attempts to build for M1 architecture, due to Github Actions lack of support for native compilation. Functioning wheels in `1.0.0.post3` and `1.0.0` should differ _only_ in their release name, but all the arm64 ones are broken.

To avoid confusion Python 3.11 wheels could be added to the `1.0.0.post3` release, or the post releases could be yanked. Not sure whether these actions would have undesired side-effects though?
