### ISSUE TITLE
Question about the toy example in error analysis paper.

### ISSUE THREAD

**Issue by Fr4nk1inCs** [LLNL/zfp#243]
In _Error Analysis of ZFP Compression for Floating-Point Data_, there is a toy example in Appendix A. After step 5, the converted negabinaries are

$$
x^{(5)} =
\begin{bmatrix}
0 & 0 & 1 & 1 & 0 & 0 & 1 & 0 & 0 & 1 & 1 \\
0 & 0 & 1 & 1 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 1 & 1 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 1 & 1 & 1
\end{bmatrix}
$$

Then $x^{(5)}$ is "transposed", variable-length encoded and output. The paper shows the result as

> Note that if Step 7 had been performed then the final compressed bit sequence would have been 0 0 11110 110 000 00110 1011, ...

I tried to encode the bits and got most bit plane correct, except the last one (7th bit plane). My result is 110010 rather than 1011. Here's how I encode (output bit with dot stands for group test)

```txt
 bit planes  | n | output
LSB      MSB |   | 
 0  0  0  0  | 0 | 0.
 0  0  0  0  | 0 | 0.
 1  1  0  0  | 0 | 1. 1  1. 1  0. 
 1  1  0  0  | 2 | 1  1  0.
 0  0  0  0  | 2 | 0  0  0.
 0  0  1  0  | 2 | 0  0  1. 1  0.
 1  0  0  1  | 3 | 1  1. 0  0  1  0.
    ....     | 4 | ....
```

Please let me know if I misunderstand something. Thanks for your time and effort on this amazing work.

**Comment by lindstro** [comment]
Actually, neither is correct.  The last bit plane is encoded as `1001`.  The first (leftmost) *n* = 3 bits are encoded verbatim, without any group tests, since the rightmost one-bit among all bit planes above is in the third position (bit plane `0010` just above).  Hence, after outputting the *n* = 3 bits `100`, only the MSB remains, for which we have a positive group test followed by no value bits since the rightmost bit is implicit in this case (it must be a one).  Hope that helps, and sorry for getting it wrong in the paper.

**Comment by Fr4nk1inCs** [comment]
Thanks for the explanation.
