### ISSUE TITLE
cases where bitstream type is used without including bitstream.h

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/zfp#71]
`zfp.h` includes `bitstream.h` and so that kinda sorta hides this issue. But, zfp applications such as the file compressor, `zfp` or the simple example use `bitstream` types without a `#include <bitstream.h>`

**Comment by lindstro** [comment]
@markcmiller86 Can you please state more clearly what the issue is?  `bitstream.h` is included in `zfp.h` by necessity, since some of the zfp API functions take a `bitstream` struct.

I should point out that the bit stream API is special in that it allows calling both nonstatic and static (inlined) versions of the same function (by including `src/inline/bitstream.c` directly).  The latter is useful for performance critical code sections, while the former makes it possible to avoid code duplication.

**Comment by markcmiller86** [comment]
In `src/utils/zfp.c`, the type `bitstream` is used as well as several methods from the bitstream API. But, there is no `#include "bitstream.h"`. I think there should be. That API is defined in `bitstream.h` isn't it. Its just a matter of current implementation that it is used (and therefore included in) `zfp.h`. In fact, the forward declaration `typedef struct bitstream bitstream;
` would elleviate any need of a `#include "bitstream.h` in `zfp.h` and would then *force* clients of ZFP library to have to include it explicitly.

**Comment by lindstro** [comment]
I see your reasoning.  However, the bit stream API is officially part of zfp and gets built with `libzfp`.  Hence, including `zfp.h` should be sufficient to expose the whole zfp API.

Note that the bit stream module has been written to be its own standalone library, independent of zfp, that can be used with other compressors; hence the lack of a `zfp_` prefix.  For example, a future rewrite of fpzip will make use of the bit stream API.

I've been pondering breaking out bitstream into its own library, in which case it might make sense to force users to include `bitstream.h` explicitly.  But rather than force the user to include two headers, I would prefer providing zfp wrappers (much like `zfp_stream_rewind`) around the most common bit stream functions (e.g., `stream_open` and `stream_close`) so that the average user does not have to include `bitstream.h`.  The main reason to expose the bit stream API at all is for the expert user (you're one of them!) who might want to embed other data in the zfp stream.

I know this isn't the cleanest solution.  I could add an explicit `#include`, but it would have no effect other than to document the dependency on bitstream.  It's not all that uncommon to break header files into multiple subfiles, and I'm guessing you're happy to just `#include <string.h>` when using `memcpy` and `strtok`, even though `size_t` and `NULL` are defined in `stddef.h`. :-)

I may also be misinterpreting your concern.  For example, compilation could be (marginally) faster by only forward declaring `struct bitstream` and omitting all `stream_` function declarations from `zfp.h`.  However, zfp is rather useless without `stream_open`.

**Comment by markcmiller86** [comment]
> I may also be misinterpreting your concern.

*concern* may be too strong a word. I just happened to notice and since I viewed these two APIs as rather distinct even if interdependent, I thought I would mention it.

And, I am likely a little more concerned with implementation than any consumer of ZFP ordinarily would be because I am embedding the lib in Silo and its implementation effects that a bit.
