### ISSUE TITLE
How to get the number of uncompressed bytes from zfp_decompress

### ISSUE THREAD

**Issue by lferraro** [LLNL/zfp#81]
Hello, I'm playing with the ZFP High level API and found that the [zfp_decompress](
https://zfp.readthedocs.io/en/release0.5.5/high-level-api.html#compression-and-decompression) function returns the number of compressed bytes found in the stream, while I was expecting to return the number of uncompressed bytes extracted from the compressed stream.

The reason I wish to know the uncompressed byte count is that, when I compress some data, I can store (say on a file) the compressed buffer and its compressed byte size, then I would read back this compressed data, uncompress them in a large enough buffer and find out which is the original dimension in bytes. 

Am I missing something? Thank you for any hint  or explanation.

**Comment by lindstro** [comment]
You cannot call `zfp_decompress` without already knowing this information.  The reason is that you have to set up a `zfp_field` structure that contains the dimensions and scalar type of the decompressed array, from which you can easily determine the number of uncompressed bytes.

As a user, you either have to store the field metadata separate from the compressed stream or you can use zfp's header mechanism, which encodes this information (see `zfp_write_header` and `zfp_read_header`).
