### ISSUE TITLE
How to get the error value and compression speed

### ISSUE THREAD

**Issue by lljjgg** [LLNL/zfp#89]
Hi：
   I use zfp to compress floating point data.and I want to get Absolute error and Compression speed.But This information is not included in the output.Can I get this information from the program?if it is possible，what should I do.Looking forward to your reply，Thank you.
lljjgg

**Comment by lindstro** [comment]
The maximum absolute error is reported as 'maxe' by the zfp command-line tool using the `-s` option.  Other error metrics are reported, as well.

Since execution time can be somewhat difficult to measure and port across operating systems, we don't include such statistics in the output of the zfp utility.  However, adding such instrumentation to `zfp.c` should be straightforward for time-critical applications.

**Comment by lljjgg** [comment]
Thanks ,I get.By the way ,I find that the CUDA implementation supports only fixed-rate mode.In the future,Will it support others mode?For example fixed accuracy.Thanks again for your reply,Thanks

**Comment by lindstro** [comment]
We are working on adding CUDA support for all of zfp's compression modes.  There are a number of challenges associated with parallel variable-rate decompression, as that requires storing an index of compressed blocks that currently is not supported by the zfp codestream.  Thus, there are necessary changes to the zfp API and format that we need to work through.

If you're interested in the technical details, then I would suggest checking out our paper that will be presented at [PDP 2020](http://www.pdp2020.com/images/ProgramList.pdf) next week.
